baseURL = "https://ryantenor.io"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Ryan Tenorio's Homepage"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
profilePicture = "images/twitter-profile-picture.jpg"
author = "Ryan Tenorio"
description = """
Welcome to my online home base!
Explore and feel free to connect with my socials below.
"""
title = "Ryan Tenorio"
displayMode = "dark"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/stefan-ryan-tenorio/"

[[params.socialIcons]]
icon = "fab fa-twitter-square"
title = "Twitter"
url = "https://www.twitter.com/leeto"

[[params.socialIcons]]
icon = "fab fa-twitch"
title = "Twitch"
url = "https://www.twitch.tv/imleeto"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
